version: '3.8'
# volumes:
#   db-vol:
services:
  dev-api:
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: ./startup-script.sh
    env_file:
      - .env
    networks:
      - dev-app
    depends_on:
      - dev-db
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - dev-app
    # @TODO: fix this: when using a volume, we should only seed once
    # volumes:
    #   - db-vol:/var/lib/postgresql/data 
networks:
  dev-app: