version: '3.8'
services:
  test-api:
    build:
      context: .
      target: development
      args:
        NODE_ENV: test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env.test
    networks:
      - test-app
    depends_on:
      - test-db
    extra_hosts:
      - "host.docker.internal:host-gateway"
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - test-app
networks:
  test-app: